name: Deploy App1

on:
  push:
    branches:
      - app1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH & Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 3.20.232.50
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app1
          git pull origin main
          pm2 restart all || pm2 start index.js --name app1
